### PR TITLE
Feature #3 Create a Firebase backend and a Firestore database

### LINKED ISSUE #3: Create a Firebase backend and a Firestore database

### PR DESCRIPTION
**Pull request by CarolineLarsen**
Closes #3

This sets up a Firebase backend and a Firestore database.

The page is hosted on: https://ci-server-assignment2.web.app/
Here it is explained how to add entries to the database: https://firebase.google.com/docs/firestore/quickstart#add_data

In order to be able to deploy changes to the page, first make sure that you have npm installed on your computer, and that your email address has been added to the project.
Then, run the following commands:

```npm install -g firebase-tools```

```firebase login```

```firebase init```

When initializing, select the existing project called "CI server assignment2". Also, make sure that you only select the two features Firestore and Hosting.
Choose the default filenames when it is asked.

After having made some changes and when it is time to deploy, run the following command:

```firebase deploy```

The changes should then be visible on the page and on Firestore if such changes has been made.

Co-authored-by: Anton Lövström <anton.lovstrom4@gmail.com>

### CODE REVIEW

**Comment by robinwanlund** [comment]
Error: Failed to get Firebase project project-name. Please make sure the project exists and your account has permission to access it

Får detta felmeddelande som respons när jag valt de två features Hosrting och Firestore

**Comment by JoakimSkoog97** [comment]
I get same problem from Linux as Robin from Windows.

**Comment by CarolineLarsen** [comment]
Your email addresses are not yet added to the project. So that is probably why it did not work.

**Review by JoakimSkoog97 — APPROVED** [review]
LGTM

**Pull request merged**
